package modelo;
// Generated 26 ene 2026, 10:16:53 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipos generated by hbm2java
 */
public class Tipos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String nameEu;
	private Set userses = new HashSet(0);

	public Tipos() {
	}

	public Tipos(String name) {
		this.name = name;
	}

	public Tipos(String name, String nameEu, Set userses) {
		this.name = name;
		this.nameEu = nameEu;
		this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEu() {
		return this.nameEu;
	}

	public void setNameEu(String nameEu) {
		this.nameEu = nameEu;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	@Override
	public String toString() {
		return "Tipos [id=" + id + ", name=" + name + ", nameEu=" + nameEu + "]";
	}

	
	
	
}
