package modelo;
// Generated Jan 19, 2026, 1:21:55 AM by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import com.google.gson.annotations.Expose;

import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

/**
 * Matriculaciones generated by hbm2java
 */
public class Matriculaciones implements java.io.Serializable {

	private Integer id;
	@ManyToOne
    @JoinColumn(name = "alum_id") // En SQL pusiste: alum_id (NO user_id)
    private Users users;

    @ManyToOne
    @JoinColumn(name = "ciclo_id") // En SQL pusiste: ciclo_id (NO id)
    private Ciclos ciclos;
	private byte curso;
	private Date fecha;

	public Matriculaciones() {
	}

	public Matriculaciones(Ciclos ciclos, Users users, byte curso, Date fecha) {
		this.ciclos = ciclos;
		this.users = users;
		this.curso = curso;
		this.fecha = fecha;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public byte getCurso() {
		return this.curso;
	}

	public void setCurso(byte curso) {
		this.curso = curso;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
